### ISSUE TITLE
API enhancement suggestion

### ISSUE THREAD

**Issue by nfroidure** [SimpliField/httptables#1]
Great work Georges ;)

Here are some suggestions for the high level API.

I think it would be more expressive if the rules were contained in the HTTP tables instance, that way, you wouldn't need to keep a ref to the rules each time you need to perform a test on them:

``` js
var httpTables = new HTTPTables(rules);
var result1 = httpTables.test(req);
var result2 = httpTables.test(req);
```

If you still want to have a rules + req function, i think it should be a static function on the HTTPTables constructor:

``` js
var result = HTTPTables.applyRules(rules, req);
```

On the policies specifically, we could improve the code expressiveness by simply documenting and using policies constants. Also, since they are constants, i think it could be set at the constructor level:

``` js
if(HTTPTables.applyRules(rules, req) == HTTPTables.policies.ACCEPT) {
  console.log('Accepted!');
}
```

Hope it helps!

**Comment by gplancke** [comment]
Hi Nicolas,

totally agree with you, will update accordingly (But you can PR if you feel like it :) )

**Comment by gplancke** [comment]
Except it is Httptables({rules: rules})
And HTTPTables returns a factory fonction :)
